name: Benchttp CI
description: Run Benchttp

inputs:
  endpoint:
    description: Endpoint to retrieve the profile from
    required: true
  service_name:
    description: Service name
    required: true
  username:
    description: ""
    required: true
  password:
    description: ""
    required: true
  output_path:
    description: Path to the output file
    required: true
  range_from:
    description: ""
    required: false
    default: now-1h
  range_to:
    description: ""
    required: false
    default: now
  profile_type:
    description: ""
    required: false
    default: process_cpu:samples:count:cpu:nanoseconds
  profilecli_version:
    description: ""
    required: false
    default: "1.1.5"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Remove previous profile if exists
      # TODO: remove only if download was successful
      shell: sh
      run: rm -f ${{ inputs.output_path }}

    - name: Download profilecli executable
      shell: sh
      run: |
        curl -fL https://github.com/grafana/pyroscope/releases/download/v${{ inputs.profilecli_version }}/profilecli_${{ inputs.profilecli_version }}_linux_amd64.tar.gz | tar xvz
        chmod +x profilecli

    - name: Download profiling
      shell: sh
      run: |
        ./profilecli query merge \
          --from="${{ inputs.range_from }}" \
          --to="${{ inputs.range_from }}" \
          --profile-type="${{ inputs.profile_type }}" \
          --query='{service_name="${{ inputs.service_name }}"}' \
          --output="pprof=${{ inputs.output_path }}" \
          --url="${{ inputs.endpoint }}" \
          --username="${{ inputs.username }}" \
          --password="${{ inputs.password }}"
